### PR TITLE
Refactor packages, dependencies, and GlobalSettings

### PR DESCRIPTION
**Pull request by fushar**

### CODE REVIEW

**Comment by dronjax** [comment]
I will look into it more tonight. But by quick looking it, I think it's quite ok.

**Comment by dronjax** [comment]
It is okay and can be merged.
Just to make sure, this is backward compatible currently right?

**Comment by fushar** [comment]
Yes, it is backward-compatible.

**Comment by dronjax** [comment]
Since this is backward compatible, I will try merging it tonight

**Comment by dronjax** [comment]
I tested this using judgels/jophiel and found this errors:

> ! @6of3pj737 - Internal server error, for (GET) [/logo] ->
> 
> play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ConfigurationException: Guice configuration errors:
> 
> 1) No implementation for java.lang.String annotated with @org.iatoki.judgels.play.general.GeneralName() was bound.
> while locating java.lang.String annotated with @org.iatoki.judgels.play.general.GeneralName()
> for parameter 1 at org.iatoki.judgels.play.general.GeneralConfig.<init>(GeneralConfig.java:19)
> while locating org.iatoki.judgels.play.general.GeneralConfig
> for field at org.iatoki.judgels.play.AbstractJudgelsController.generalConfig(AbstractJudgelsController.java:34)
> while locating org.iatoki.judgels.play.JudgelsPlayCommonsController
> 
> 2) No implementation for java.lang.String annotated with @org.iatoki.judgels.play.general.GeneralVersion() was bound.
> while locating java.lang.String annotated with @org.iatoki.judgels.play.general.GeneralVersion()
> for parameter 2 at org.iatoki.judgels.play.general.GeneralConfig.<init>(GeneralConfig.java:19)
> while locating org.iatoki.judgels.play.general.GeneralConfig
> for field at org.iatoki.judgels.play.AbstractJudgelsController.generalConfig(AbstractJudgelsController.java:34)
> while locating org.iatoki.judgels.play.JudgelsPlayCommonsController
> 
> 3) No implementation for org.iatoki.judgels.Config annotated with @org.iatoki.judgels.play.general.GeneralConfigSource() was bound.
> while locating org.iatoki.judgels.Config annotated with @org.iatoki.judgels.play.general.GeneralConfigSource()
> for parameter 0 at org.iatoki.judgels.play.general.GeneralConfig.<init>(GeneralConfig.java:19)
> while locating org.iatoki.judgels.play.general.GeneralConfig
> for field at org.iatoki.judgels.play.AbstractJudgelsController.generalConfig(AbstractJudgelsController.java:34)
> while locating org.iatoki.judgels.play.JudgelsPlayCommonsController
> 
> 3 errors]]
> at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.6.jar:2.4.6]
> at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
> at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
> at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
> at scala.Option.getOrElse(Option.scala:121) [scala-library-2.11.7.jar:na]
> at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
> at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.6.jar:2.4.6]
> at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [play-netty-server_2.11-2.4.6.jar:2.4.6]
> at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [play-netty-server_2.11-2.4.6.jar:2.4.6]
> at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
> at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
> at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
> at scala.util.Failure.recover(Try.scala:216) [scala-library-2.11.7.jar:na]
> at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
> at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
> at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
> at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.6.jar:2.4.6]
> at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.6.jar:2.4.6]
> at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
> at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
> at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
> at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
> at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.7.jar:na]
> at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
> at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
> at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
> at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
> at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
> at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
> Caused by: com.google.inject.ConfigurationException: Guice configuration errors:
> 
> 1) No implementation for java.lang.String annotated with @org.iatoki.judgels.play.general.GeneralName() was bound.
> while locating java.lang.String annotated with @org.iatoki.judgels.play.general.GeneralName()
> for parameter 1 at org.iatoki.judgels.play.general.GeneralConfig.<init>(GeneralConfig.java:19)
> while locating org.iatoki.judgels.play.general.GeneralConfig
> for field at org.iatoki.judgels.play.AbstractJudgelsController.generalConfig(AbstractJudgelsController.java:34)
> while locating org.iatoki.judgels.play.JudgelsPlayCommonsController
> 
> 2) No implementation for java.lang.String annotated with @org.iatoki.judgels.play.general.GeneralVersion() was bound.
> while locating java.lang.String annotated with @org.iatoki.judgels.play.general.GeneralVersion()
> for parameter 2 at org.iatoki.judgels.play.general.GeneralConfig.<init>(GeneralConfig.java:19)
> while locating org.iatoki.judgels.play.general.GeneralConfig
> for field at org.iatoki.judgels.play.AbstractJudgelsController.generalConfig(AbstractJudgelsController.java:34)
> while locating org.iatoki.judgels.play.JudgelsPlayCommonsController
> 
> 3) No implementation for org.iatoki.judgels.Config annotated with @org.iatoki.judgels.play.general.GeneralConfigSource() was bound.
> while locating org.iatoki.judgels.Config annotated with @org.iatoki.judgels.play.general.GeneralConfigSource()
> for parameter 0 at org.iatoki.judgels.play.general.GeneralConfig.<init>(GeneralConfig.java:19)
> while locating org.iatoki.judgels.play.general.GeneralConfig
> for field at org.iatoki.judgels.play.AbstractJudgelsController.generalConfig(AbstractJudgelsController.java:34)
> while locating org.iatoki.judgels.play.JudgelsPlayCommonsController
> 
> 3 errors
>   at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042) ~[guice-4.0.jar:na]
> at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001) ~[guice-4.0.jar:na]
> at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
> at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.6.jar:2.4.6]
> at playcommons.Routes$$anonfun$routes$1$$anonfun$applyOrElse$4$$anonfun$apply$24.apply(Routes.scala:270) ~[classes/:na]
> at playcommons.Routes$$anonfun$routes$1$$anonfun$applyOrElse$4$$anonfun$apply$24.apply(Routes.scala:270) ~[classes/:na]
> at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.GlobalSettings$1.call(GlobalSettings.java:67) ~[play_2.11-2.4.6.jar:2.4.6]
> at org.iatoki.judgels.play.controllers.UnsupportedOperationGuardAction.call(UnsupportedOperationGuardAction.java:21) ~[classes/:na]
> at org.iatoki.judgels.play.controllers.EntityNotFoundGuardAction.call(EntityNotFoundGuardAction.java:22) ~[classes/:na]
> at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[play_2.11-2.4.6.jar:2.4.6]
> at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.7.jar:na]
> at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.7.jar:na]
> at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) [play-iteratees_2.11-2.4.6.jar:2.4.6]
> at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[play_2.11-2.4.6.jar:2.4.6]
> at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[scala-library-2.11.7.jar:na]
> at scala.concurrent.Future$.apply(Future.scala:492) ~[scala-library-2.11.7.jar:na]
> at play.core.j.JavaAction.apply(JavaAction.scala:94) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.11-2.4.6.jar:2.4.6]
> at scala.Option.map(Option.scala:146) [scala-library-2.11.7.jar:na]
> at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.11-2.4.6.jar:2.4.6]
> at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
> at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
> at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
> at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
> at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
> at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
> at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.7.jar:na]
> at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.7.jar:na]
> ... 6 common frames omitted

Logo also cannot render.

**Comment by fushar** [comment]
Oh, you're right... it's not so "backward-compatible" as you have to modify your `application.conf`. I'll show how to do it in Sealtiel.

**Comment by fushar** [comment]
Something like this:

https://github.com/judgels/sealtiel/commit/6595cab2313f5cbd71618a681c6b46cb33801df8#diff-922a6196409524c9e1ce7e2146bf1a9bR1

After this is merged, I will change all other `application_default.conf`.

**Comment by dronjax** [comment]
I followed that, and this happen:

> CreationException: Unable to create injector, see the following errors:
> 
> 1) No implementation for org.iatoki.judgels.play.migration.BaseDataMigrationService was bound.
>   while locating org.iatoki.judgels.play.migration.BaseDataMigrationService
>     for parameter 1 at org.iatoki.judgels.play.migration.DataMigrationInit.<init>(DataMigrationInit.java:12)
>   at org.iatoki.judgels.play.JudgelsPlayCommonsModule.configure(JudgelsPlayCommonsModule.java:16) (via modules: com.google.inject.util.Modules$OverrideModule -> org.iatoki.judgels.play.JudgelsPlayCommonsModule)
> 
> 1 error

I think you should do pull request on all other conf as well.

By the way my jophiel.conf looks like this:

> # Application configuration
> 
> application {
>   title = "Single Sign On"
>   copyright = "TLX"
> }
> 
> general {
>   title = "Single Sign On"
>   copyright = "TLX"
>   canonicalUrl = "http://jophiel.local.ia-toki.org"
>   githubUrl = "https://github.com/ia-toki/judgels-jophiel"
> }
> 
> play {
>   application.loader = "org.iatoki.judgels.jophiel.config.JophielApplicationLoader"
> 
>   # The secret key used to secure cryptographics functions.
>   # See http://www.playframework.com/documentation/latest/ApplicationSecret for more details.
>   crypto.secret="`b[7nm_OpCXwsRsVyDy7yxcqDqq[K60]h^kK<ZY`b`1?EH?N_/R0GqS9:G@5ngXQ"
> 
>   http {
>     # Cookie variable name when saving session in client side
>     session.cookieName = "JOPHIEL_SESSION"
>     # Use HTTPS?
>     session.secure = false
>     filters = "org.iatoki.judgels.play.Filters"
>   }
> 
>   modules {
>     enabled += "org.iatoki.judgels.play.JudgelsPlayCommonsModule"
>     enabled += "org.iatoki.judgels.play.seo.SeoModule"
>     enabled += "org.iatoki.judgels.jophiel.config.JophielModule"
>     enabled += "com.typesafe.play.redis.RedisModule"
>     enabled += "play.api.libs.mailer.MailerModule"
>     enabled += "org.iatoki.judgels.jophiel.config.JophielModule"
>   }

I still need to enable application and link namespace conf, or it will not work.

This need major refactor and I suggest you should do it without pull requests.

**Comment by fushar** [comment]
Added a commit.

@dragoon20 Please merge this, and after that I will push module fixes for all judgels apps.

**Comment by dronjax** [comment]
Merged, still not working with current Jophiel (and possibly others). Please fix that.

**Pull request closed without merging**
